config/routes.rb
Primero::Application.routes.draw do
  match '/' => 'home#index', :as => :root, :via => :get
  match '/_notify_change' => 'couch_changes#notify', :via => :get

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

#######################
# USER URLS
#######################

  resources :users do
    collection do
      get :change_password
      get :unverified
      post :update_password
      post :import_file
    end
  end
  match '/users/register_unverified' => 'users#register_unverified', :as => :register_unverified_user, :via => :post

  resources :sessions, :except => :index
  match 'login' => 'sessions#new', :as => :login, :via => [:post, :get, :put, :delete]
  match 'logout' => 'sessions#destroy', :as => :logout, :via => [:post, :get, :put, :delete]
  match '/active' => 'sessions#active', :as => :session_active, :via => [:post, :get, :put, :delete]

  resources :user_preferences
  resources :password_recovery_requests, :only => [:new, :create]
  match 'password_recovery_request/:password_recovery_request_id/hide' => 'password_recovery_requests#hide', :as => :hide_password_recovery_request, :via => :delete

  resources :contact_information

  resources :system_settings, only: [:show, :edit, :update]
  resources :saved_searches, only: [:create, :index, :show, :destroy]
  resources :matching_configurations, only: [:show, :edit, :update]

  resources :roles do
    collection do
      post :import_file
    end
  end

  match '/roles/:id/copy' => 'roles#copy', :as => :copy_role, :via => [:post]

  resources :user_groups
  resources :primero_modules
  resources :primero_programs
  resources :agencies do
    collection do
      post :update_order
    end
  end

#######################
# CHILD URLS
#######################

  resources :children do
    collection do
      post :import_file
      get :search
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

  resources :children, as: :cases, path: :cases do
    collection do
      post :import_file
      post :transition
      post :mark_for_mobile
      post :approve_form
      post :add_note
      put :request_transfer
      get :search
      get :consent_count
    end

    member do
      put :match_record
      put :transfer_status
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

#######################
# TRACING REQUESTS URLS
#######################
  resources :tracing_requests, as: :tracing_requests, path: :tracing_requests do
    collection do
      post :import_file
      get :search
    end

    resources :attachments, :only => :show
  end


  match '/children-ids' => 'child_ids#all', :as => :child_ids, :via => [:post, :get, :put, :delete]
  match '/children/:id/photo/edit' => 'children#edit_photo', :as => :edit_photo, :via => :get
  match '/children/:id/photo' => 'children#update_photo', :as => :update_photo, :via => :put
  match '/children/:child_id/photos_index' => 'child_media#index', :as => :photos_index, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photos' => 'child_media#manage_photos', :as => :manage_photos, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/document/:document_id' => 'child_media#download_document', :as => :child_document, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/audio(/:id)' => 'child_media#download_audio', :as => :child_audio, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id' => 'child_media#show_photo', :as => :child_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo' => 'child_media#show_photo', :as => :child_legacy_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :child_select_primary_photo, :via => :put
  match '/children/:child_id/resized_photo/:size' => 'child_media#show_resized_photo', :as => :child_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id/resized/:size' => 'child_media#show_resized_photo', :as => :child_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/thumbnail(/:photo_id)' => 'child_media#show_thumbnail', :as => :child_thumbnail, :via => [:post, :get, :put, :delete]
  match '/children' => 'children#index', :as => :child_filter, :via => [:post, :get, :put, :delete]

  match '/agency/:agency_id/logo/:logo_id' => 'agency_media#show_logo', :as => :agency_logo, :via => [:get]

  match '/case-ids' => 'child_ids#all', :as => :case_ids, :via => [:post, :get, :put, :delete]
  match '/cases/:id/photo/edit' => 'children#edit_photo', :as => :edit_case_photo, :via => :get
  match '/cases/:id/photo' => 'children#update_photo', :as => :update_case_photo, :via => :put
  match '/cases/:child_id/photos_index' => 'child_media#index', :as => :case_photos_index, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photos' => 'child_media#manage_photos', :as => :manage_case_photos, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/audio(/:id)' => 'child_media#download_audio', :as => :case_audio, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo/:photo_id' => 'child_media#show_photo', :as => :case_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo' => 'child_media#show_photo', :as => :case_legacy_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :case_select_primary_photo, :via => :put
  match '/cases/:child_id/resized_photo/:size' => 'child_media#show_resized_photo', :as => :case_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo/:photo_id/resized/:size' => 'child_media#show_resized_photo', :as => :case_resized_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/thumbnail(/:photo_id)' => 'child_media#show_thumbnail', :as => :case_thumbnail, :via => [:post, :get, :put, :delete]
  match '/cases' => 'children#index', :as => :case_filter, :via => [:post, :get, :put, :delete]
  match '/cases/:id/hide_name' => 'children#hide_name', :as => :child_hide_name, :via => :post

  match '/incident-ids' => 'incident_ids#all', :as => :incident_ids, :via => [:post, :get, :put, :delete]

#Route to create a Incident from a Case, this is mostly for the show page. User can create from the edit as well which goes to the update controller.
  match '/cases/:child_id/create_incident' => 'children#create_incident', :as => :child_create_incident, :via => :get
  match '/cases/:child_id/create_subform' => 'children#create_subform', :as => :child_create_subform, :via => :get
  match '/cases/:child_id/save_subform' => 'children#save_subform', :as => :child_save_subform, :via => [:post, :put]
  match '/cases/:child_id/quick_view' => 'children#quick_view', :as => :child_quick_view, :via => :get
  match '/cases/:child_id/request_transfer_view' => 'children#request_transfer_view', :as => :request_transfer_view, :via => :get


#Flag routing
  match '/cases/:id/flag' => 'record_flag#flag', :as => :child_flag, model_class: 'Child', :via => [:post, :put]
  match '/incidents/:id/flag' => 'record_flag#flag', :as => :incident_flag, model_class: 'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/flag' => 'record_flag#flag', :as => :tracing_request_flag, model_class: 'TracingRequest', :via => [:post, :put]

#Flag multiple records routing
  match '/cases/flag_records' => 'record_flag#flag_records', :as => :child_flag_records, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/flag_records' => 'record_flag#flag_records', :as => :incident_flag_records, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/flag_records' => 'record_flag#flag_records', :as => :tracing_request_flag_records, :model_class => 'TracingRequest', :via => [:post, :put]

# Set Record Status
  match '/cases/record_status' => 'record_status#set_record_status', :as => :child_record_status, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/record_status' => 'record_status#set_record_status', :as => :incident_record_status, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/record_status' => 'record_status#set_record_status', :as => :tracing_request_record_status, :model_class => 'TracingRequest', :via => [:post, :put]

  # Set Case Status on reopening
  match '/cases/:id/reopen_case' => 'children#reopen_case', :as => :child_reopen_case, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/request_approval' => 'children#request_approval', :as => :child_request_approval, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/transfer_status' => 'children#transfer_status', :as => :child_transfer_status, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/relinquish_referral' => 'children#relinquish_referral', :as => :child_relinquish_referral, :model_class => 'Child', :via => [:post, :put]

  # Download forms spreadsheet
  match '/forms/download' => 'form_section#download_all_forms', :as => :download_forms, :via => [:get]

  #Unflag routing
  match '/cases/:id/unflag' => 'record_flag#unflag', :as => :child_unflag, model_class:'Child', :via => [:post, :put]
  match '/incidents/:id/unflag' => 'record_flag#unflag', :as => :incident_unflag, model_class:'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/unflag' => 'record_flag#unflag', :as => :tracing_request_unflag, model_class:'TracingRequest', :via => [:post, :put]

  match '/tracing_requests-ids' => 'tracing_request_ids#all', :as => :tracing_request_ids, :via => [:post, :get, :put, :delete]

app/models/transition.rb
class Transition
  include Syncable::PrimeroEmbeddedModel
  include PrimeroModel

  validate :validate_record

  property :type, String
  property :to_user_local, String
  property :to_user_remote, String
  property :to_user_agency, String
  property :to_user_local_status, String
  property :rejected_reason, String
  property :notes, String
  property :transitioned_by, String
  property :service, String #service referers to the 'Type of Service'
  property :is_remote, TrueClass
  property :type_of_export, String
  property :consent_overridden, TrueClass
  property :consent_individual_transfer, TrueClass
  property :created_at, Date
  property :id

  TYPE_REFERRAL = "referral"
  TYPE_REASSIGN = "reassign"
  TYPE_TRANSFER = "transfer"
  TYPE_TRANSFER_REQUEST = "transfer_request"

  TRANSFERRED_STATUS = 'transferred'

  TO_USER_LOCAL_STATUS_PENDING = "pending"
  TO_USER_LOCAL_STATUS_ACCEPTED = "accepted"
  TO_USER_LOCAL_STATUS_REJECTED = "rejected"
  TO_USER_LOCAL_STATUS_DONE = "done"
  TO_USER_LOCAL_STATUS_INPROGRESS = "in_progress"

  def initialize *args
    super

    self.id ||= UUIDTools::UUID.random_create.to_s
  end

  def parent_record
    base_doc
  end

  def is_referral_active?
    self.to_user_local_status == Transition::TO_USER_LOCAL_STATUS_INPROGRESS
  end

  def is_transfer_in_progress?
    self.to_user_local_status == Transition::TO_USER_LOCAL_STATUS_INPROGRESS
  end

  def is_assigned_to_user_local?(user)
    self.to_user_local == user
  end

  private

  def validate_record
    #TODO
  end
end

app/views/transitions/_button.html.erb
<%
    model_class_name = controller.model_class.name.underscore.downcase
    model_name = I18n.t("forms.record_types.#{model_class_name}")
    module_users = @module_users || []
    transition_type = type || "referral"

    if transition_type == "referral"
      transition_role_options = @referral_roles.map {|r| [r.name, r.id]}
      no_consent_count = ((@referral_consent.present? && @referral_consent == true) ? 0 : 1)
      type_of_export_options = [
          [I18n.t("transition.export_type.#{Transitionable::EXPORT_TYPE_PRIMERO}"), Transitionable::EXPORT_TYPE_PRIMERO],
          [I18n.t("transition.export_type.#{Transitionable::EXPORT_TYPE_NON_PRIMERO}"), Transitionable::EXPORT_TYPE_NON_PRIMERO],
          [I18n.t("transition.export_type.#{Transitionable::EXPORT_TYPE_PDF}"), Transitionable::EXPORT_TYPE_PDF]]
    elsif transition_type == "transfer"
      transition_role_options = @transfer_roles.map {|r| [r.name, r.id]}
      no_consent_count = ((@transfer_consent.present? && @transfer_consent == true) ? 0 : 1)
      type_of_export_options = [
          [I18n.t("transition.export_type.#{Transitionable::EXPORT_TYPE_PRIMERO}"), Transitionable::EXPORT_TYPE_PRIMERO],
          [I18n.t("transition.export_type.#{Transitionable::EXPORT_TYPE_NON_PRIMERO}"), Transitionable::EXPORT_TYPE_NON_PRIMERO]]
    else
      transition_role_options = []
      no_consent_count = 0
      type_of_export_options = []
    end
%>
<% if can?(transition_type.to_sym(), controller.model_class) %>
<li>
  <a data-consent_count_url="<%= "/#{model_name.downcase.underscore.pluralize}/consent_count" %>"
     data-open=<%= "#{transition_type}-modal" %> class=<%= (defined?(instance) ? "#{transition_type}_show_action" : "#{transition_type}_index_action") %>>
     <%= t("buttons.#{transition_type}", model: model_name) %>
  </a>

  <div id=<%= "#{transition_type}-modal" %> class="reveal tiny" data-reveal>
    <%= render 'shared/modal_close' %>
    <div class=<%= "#{transition_type}_form_container row"%> >
      <div class="large-12">
        <%= form_tag(url_for(:action => 'transition', :id => (defined?(instance) ? instance.id : nil)), {:multipart => true, :method => 'post', :autocomplete => "off"}) do %>
          <%= hidden_field_tag "selected_records"%>
          <%= hidden_field_tag "transition_type", transition_type%>
          <%= hidden_field_tag "service_object_id" %>
          <% if transition_type == Transition::TYPE_REASSIGN %>
            <%= t("reassign.reassign_case_title") %>
          <% else %>
            <label class="consent">
              <span class="consent_count"><%= no_consent_count%></span>
              <%=I18n.t("#{transition_type}.consent_label")%>
            </label>
            <% if can?(:consent_override, controller.model_class) %>
              <%= check_box_tag("consent_override", "true") %>
              <label for="consent_override"><%=I18n.t("#{transition_type}.consent_override_label")%></label>
            <% end %>
            <br>
            <%= check_box_tag("is_remote", "true") %>
            <label for="is_remote"><%=I18n.t("#{transition_type}.is_remote_label")%></label>
            <% if transition_type == Transition::TYPE_TRANSFER %>
              <br>
              <div class="consent_individual_transfer">
              <%= check_box_tag("consent_individual_transfer", "true") %>
              <label for="consent_individual_transfer"><%=I18n.t("transfer.consent_individual_transfer")%></label>
              </div>
            <% end %>
          <% end %>
          <div class="local_toggle">
            <div class='local_user_flash hide_element'><p class='error'></p></div>
            <%= hidden_field_tag "existing_user", "", {:id => "existing_user_hidden"} %>
            <label><%=I18n.t("#{transition_type}.existing_user_label")%>
              <%= select_tag("existing_user", options_for_select(module_users, ''), {:include_blank => true, :class => 'chosen-select'}) %>
            </label>
          </div>
          <div class="remote_toggle" style="display:none">
            <label><%=I18n.t("#{transition_type}.type_label")%>
              <%= select_tag("transition_role", options_for_select(transition_role_options, '')) %>
            </label>
            <div class='remote_user_flash hide_element'><p class='error'></p></div>
            <label><%=I18n.t("#{transition_type}.other_user_label")%>
              <%= text_field_tag("other_user") %>
            </label>
            <label><%=I18n.t("#{transition_type}.other_user_agency_label")%>
              <%= text_field_tag("other_user_agency") %>
            </label>
          </div>
          <% if transition_type == "referral" %>
            <%= hidden_field_tag "service" , "", {:id => "service_hidden"}%>
            <label><%=I18n.t("referral.service_label")%>
              <%= select_tag("service", options_for_select(Lookup.values_for_select('lookup-service-type', @lookups), ''), :include_blank => true) %>
            </label>
          <% end %>
          <label><%=I18n.t("#{transition_type}.notes_label")%>
            <%= text_area_tag("notes") %>
          </label>
          <div class="remote_toggle" style="display:none">
            <label><%=I18n.t("#{transition_type}.type_of_export")%>
              <%= select_tag("type_of_export", options_for_select(type_of_export_options)) %>
            </label>
            <div class='password_flash hide_element'><p class='error'></p></div>
            <label><%=I18n.t("encrypt.password_label")%>
              <%= password_field_tag("password") %>
            </label>
            <small><%= t("encrypt.password_extra_info") %></small>
            <label><%=I18n.t("encrypt.file_name")%>
              <%= text_field_tag("file_name") %>
            </label>
          </div>
          <div class="row align-right">
            <div class="button-group">
              <%= submit_tag(t("buttons.submit"), class: 'button right') %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</li>
<% end %>

app/views/transitions/_refer_from_service_button.html.erb
<%
	if formObject.present? && service_object_id.present?
    service_object = formObject.services_section.select {|s| s.unique_id == service_object_id}.first
    service_type = formObject.service_field_value(service_object, 'service_type')
    service_user_name = formObject.service_field_value(service_object, 'service_implementing_agency_individual')

  else
    service_object = nil
  end
%>
<% if service_type.present? && service_user_name.present? %>
  <% if service_object.try(:service_status_referred).present?
      service_referral_button_class = 'refer_again_link service_referral_button'
      model_name = "again"
    else
      service_referral_button_class = 'button service_referral_button' 
      model_name = ""
    end
  %>
<a data-consent_count_url="cases/consent_count"
	data-service-type="<%= service_type %>"
	data-service-user-name="<%= service_user_name %>"
  data-service-object-id="<%= service_object_id %>"
 	data-open=<%= "referral-modal"%> class="<%= service_referral_button_class %>">
 	<%= t("buttons.referral", model: model_name) %>
</a>
<% end %>

app/views/transitions/_transition_done_button.html.erb
<a data-open="transition-done-modal" class="transition_done_show_action button"><%= t('buttons.done') %></a>
<div id="transition-done-modal" class="reveal tiny" data-reveal>
  <%= render 'shared/modal_close' %>
  <div class="transition_done_form_container row">
    <div class="large-11">
      <div class="row">
        <div class="medium-12 columns">
          <label><%= t("referral.complete_referral_label") %></label>
        </div>
      </div>
      <%= form_tag(child_relinquish_referral_path, :method => 'post') do %>
        <%= hidden_field_tag("transition_id", transition_id) %>
        <div class="import_button">
            <%= submit_tag(t("buttons.ok"), class: 'button right') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transitions/_transition_status_button.html.erb
<a data-open="transition-status-<%= dialog_key %>-modal" class="transition_status_<%= dialog_key %>_show_action button"><%= button_label %></a>
<div id="transition-status-<%= dialog_key %>-modal" class="reveal tiny" data-reveal>
  <%= render 'shared/modal_close' %>
  <div class="transition_status_<%= dialog_key %>_form_container row">
    <div class="large-11">
      <%= form_tag(child_transfer_status_path, :method => 'post') do %>
        <%= hidden_field_tag("transition_id", transition_id) %>
        <%= hidden_field_tag("transition_status", transition_status) %>
        <label><%= transfer_dialog_text %></label>
        <% if dialog_key == Transition::TO_USER_LOCAL_STATUS_REJECTED %>
        <label><%=I18n.t("transfer.reject")%>
          <%= text_area_tag("rejected_reason") %>
        </label>
        <% end %>
        <div class="row align-right">
          <div class="button-group">
          <% if dialog_key == Transition::TO_USER_LOCAL_STATUS_REJECTED %>
            <%= submit_tag(t("buttons.reject"), class: 'button right') %>
          <% else %>
            <%= submit_tag(t("buttons.accept"), class: 'button right') %>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>