config/routes.rb
Primero::Application.routes.draw do
  match '/' => 'home#index', :as => :root, :via => :get
  match '/_notify_change' => 'couch_changes#notify', :via => :get

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

#######################
# USER URLS
#######################

  resources :users do
    collection do
      get :change_password
      get :unverified
      post :update_password
      post :import_file
    end
  end
  match '/users/register_unverified' => 'users#register_unverified', :as => :register_unverified_user, :via => :post

  resources :sessions, :except => :index
  match 'login' => 'sessions#new', :as => :login, :via => [:post, :get, :put, :delete]
  match 'logout' => 'sessions#destroy', :as => :logout, :via => [:post, :get, :put, :delete]
  match '/active' => 'sessions#active', :as => :session_active, :via => [:post, :get, :put, :delete]

  resources :user_preferences
  resources :password_recovery_requests, :only => [:new, :create]
  match 'password_recovery_request/:password_recovery_request_id/hide' => 'password_recovery_requests#hide', :as => :hide_password_recovery_request, :via => :delete

  resources :contact_information

  resources :system_settings, only: [:show, :edit, :update]
  resources :saved_searches, only: [:create, :index, :show, :destroy]
  resources :matching_configurations, only: [:show, :edit, :update]

  resources :roles do
    collection do
      post :import_file
    end
  end

  match '/roles/:id/copy' => 'roles#copy', :as => :copy_role, :via => [:post]

  resources :user_groups
  resources :primero_modules
  resources :primero_programs
  resources :agencies do
    collection do
      post :update_order
    end
  end

#######################
# CHILD URLS
#######################

  resources :children do
    collection do
      post :import_file
      get :search
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

  resources :children, as: :cases, path: :cases do
    collection do
      post :import_file
      post :transition
      post :mark_for_mobile
      post :approve_form
      post :add_note
      put :request_transfer
      get :search
      get :consent_count
    end

    member do
      put :match_record
      put :transfer_status
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

#######################
# TRACING REQUESTS URLS
#######################
  resources :tracing_requests, as: :tracing_requests, path: :tracing_requests do
    collection do
      post :import_file
      get :search
    end

    resources :attachments, :only => :show
  end


  match '/children-ids' => 'child_ids#all', :as => :child_ids, :via => [:post, :get, :put, :delete]
  match '/children/:id/photo/edit' => 'children#edit_photo', :as => :edit_photo, :via => :get
  match '/children/:id/photo' => 'children#update_photo', :as => :update_photo, :via => :put
  match '/children/:child_id/photos_index' => 'child_media#index', :as => :photos_index, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photos' => 'child_media#manage_photos', :as => :manage_photos, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/document/:document_id' => 'child_media#download_document', :as => :child_document, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/audio(/:id)' => 'child_media#download_audio', :as => :child_audio, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id' => 'child_media#show_photo', :as => :child_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo' => 'child_media#show_photo', :as => :child_legacy_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :child_select_primary_photo, :via => :put
  match '/children/:child_id/resized_photo/:size' => 'child_media#show_resized_photo', :as => :child_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/photo/:photo_id/resized/:size' => 'child_media#show_resized_photo', :as => :child_resized_photo, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/thumbnail(/:photo_id)' => 'child_media#show_thumbnail', :as => :child_thumbnail, :via => [:post, :get, :put, :delete]
  match '/children' => 'children#index', :as => :child_filter, :via => [:post, :get, :put, :delete]

  match '/agency/:agency_id/logo/:logo_id' => 'agency_media#show_logo', :as => :agency_logo, :via => [:get]

  match '/case-ids' => 'child_ids#all', :as => :case_ids, :via => [:post, :get, :put, :delete]
  match '/cases/:id/photo/edit' => 'children#edit_photo', :as => :edit_case_photo, :via => :get
  match '/cases/:id/photo' => 'children#update_photo', :as => :update_case_photo, :via => :put
  match '/cases/:child_id/photos_index' => 'child_media#index', :as => :case_photos_index, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photos' => 'child_media#manage_photos', :as => :manage_case_photos, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/audio(/:id)' => 'child_media#download_audio', :as => :case_audio, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo/:photo_id' => 'child_media#show_photo', :as => :case_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo' => 'child_media#show_photo', :as => :case_legacy_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :case_select_primary_photo, :via => :put
  match '/cases/:child_id/resized_photo/:size' => 'child_media#show_resized_photo', :as => :case_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/photo/:photo_id/resized/:size' => 'child_media#show_resized_photo', :as => :case_resized_photo, :via => [:post, :get, :put, :delete]
  match '/cases/:child_id/thumbnail(/:photo_id)' => 'child_media#show_thumbnail', :as => :case_thumbnail, :via => [:post, :get, :put, :delete]
  match '/cases' => 'children#index', :as => :case_filter, :via => [:post, :get, :put, :delete]
  match '/cases/:id/hide_name' => 'children#hide_name', :as => :child_hide_name, :via => :post

  match '/incident-ids' => 'incident_ids#all', :as => :incident_ids, :via => [:post, :get, :put, :delete]

#Route to create a Incident from a Case, this is mostly for the show page. User can create from the edit as well which goes to the update controller.
  match '/cases/:child_id/create_incident' => 'children#create_incident', :as => :child_create_incident, :via => :get
  match '/cases/:child_id/create_subform' => 'children#create_subform', :as => :child_create_subform, :via => :get
  match '/cases/:child_id/save_subform' => 'children#save_subform', :as => :child_save_subform, :via => [:post, :put]
  match '/cases/:child_id/quick_view' => 'children#quick_view', :as => :child_quick_view, :via => :get
  match '/cases/:child_id/request_transfer_view' => 'children#request_transfer_view', :as => :request_transfer_view, :via => :get


#Flag routing
  match '/cases/:id/flag' => 'record_flag#flag', :as => :child_flag, model_class: 'Child', :via => [:post, :put]
  match '/incidents/:id/flag' => 'record_flag#flag', :as => :incident_flag, model_class: 'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/flag' => 'record_flag#flag', :as => :tracing_request_flag, model_class: 'TracingRequest', :via => [:post, :put]

#Flag multiple records routing
  match '/cases/flag_records' => 'record_flag#flag_records', :as => :child_flag_records, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/flag_records' => 'record_flag#flag_records', :as => :incident_flag_records, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/flag_records' => 'record_flag#flag_records', :as => :tracing_request_flag_records, :model_class => 'TracingRequest', :via => [:post, :put]

# Set Record Status
  match '/cases/record_status' => 'record_status#set_record_status', :as => :child_record_status, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/record_status' => 'record_status#set_record_status', :as => :incident_record_status, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/record_status' => 'record_status#set_record_status', :as => :tracing_request_record_status, :model_class => 'TracingRequest', :via => [:post, :put]

  # Set Case Status on reopening
  match '/cases/:id/reopen_case' => 'children#reopen_case', :as => :child_reopen_case, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/request_approval' => 'children#request_approval', :as => :child_request_approval, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/transfer_status' => 'children#transfer_status', :as => :child_transfer_status, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/relinquish_referral' => 'children#relinquish_referral', :as => :child_relinquish_referral, :model_class => 'Child', :via => [:post, :put]

  # Download forms spreadsheet
  match '/forms/download' => 'form_section#download_all_forms', :as => :download_forms, :via => [:get]

  #Unflag routing
  match '/cases/:id/unflag' => 'record_flag#unflag', :as => :child_unflag, model_class:'Child', :via => [:post, :put]
  match '/incidents/:id/unflag' => 'record_flag#unflag', :as => :incident_unflag, model_class:'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/unflag' => 'record_flag#unflag', :as => :tracing_request_unflag, model_class:'TracingRequest', :via => [:post, :put]

  match '/tracing_requests-ids' => 'tracing_request_ids#all', :as => :tracing_request_ids, :via => [:post, :get, :put, :delete]

app/views/home/_case_count_risk_totals.html.erb
<% @risk_levels.each do | risk_level| %>
  <%= display_stat_detailed({
    name: :risk_level,
    stat: "#{risk_level}_total".to_sym,
    filters: [
      "child_status=#{Record::STATUS_OPEN}",
      "risk_level=#{risk_level}",
      'record_state=true'
    ],
    additional_details: [
      {
        stat: risk_level.to_sym,
        filters: [
          "child_status=#{Record::STATUS_OPEN}",
          "risk_level=#{risk_level}",
          'new_other',
          'record_state=true'
        ],
        text: t('dashboard.new')
      }
    ],
    stats: stats,
    model: model,
    text: t("dashboard.#{risk_level}_risk"),
  }) %>
<% end %>

app/views/home/_case_count_services_implemented.html.erb
<%= display_stat({
  name: :services_implemented,
  stat: :total,
  stats: stats,
  model: model,
  text: t('dashboard.all_services_implemented'),
  filters: [
    "child_status=#{Record::STATUS_OPEN}",
    'record_state=true',
    "workflow=#{Child::WORKFLOW_SERVICE_IMPLEMENTED}"
  ]
}) %>

app/views/home/_case_count_transfers_by_status.html.erb
<%= display_stat({
  name: :transfer_status,
  stat: :pending,
  stats: stats,
  model: model,
  text: t('dashboard.pending_transfers'),
  filters: [
    "child_status=#{Record::STATUS_OPEN}",
    "transfer_status=#{Transition::TO_USER_LOCAL_STATUS_INPROGRESS}",
    'record_state=true',
    "owned_by=#{current_user.user_name}"
  ]
}) %>

<%= display_stat({
  name: :transfer_status,
  stat: :rejected,
  stats: stats,
  model: model,
  text: t('dashboard.rejected_transfers'),
  filters: [
    "child_status=#{Record::STATUS_OPEN}",
    "transfer_status=#{Transition::TO_USER_LOCAL_STATUS_REJECTED}",
    'record_state=true',
    "owned_by=#{current_user.user_name}"
  ]
}) %>

app/views/home/_case_manager_cases_to_assign.html.erb
<%= display_stat_detailed({
  name: :cases_to_assign,
  stat: nil,
  filters: [],
  additional_details: build_dashboard_risk_details(false),
  stats: stats,
  model: model,
  text: t('dashboard.cases_to_assign'),
}) %>

app/views/home/_case_manager_cases_to_assign_overdue.html.erb
<%= display_stat_detailed({
  name: :cases_to_assign,
  stat: nil,
  filters: [],
  additional_details: build_dashboard_risk_details(true),
  stats: stats,
  model: model,
  text: t('dashboard.overdue_cases_to_assign'),
}) %>

app/views/home/_case_manager_task_overdue.html.erb
<div class="panel">
  <div class="panel_header">
    <h4><%= t('dashboard.cases_by_task_overdue') %></h4>
    <table cellspacing="0" cellpadding="0" class="table-counts table-floating-header">
      <thead>
      <tr>
        <th><%= t('dashboard.case_worker') %></th>
        <th><%= t('dashboard.assessment') %></th>
        <th><%= t('dashboard.case_plan') %></th>
        <th><%= t('dashboard.follow_up') %></th>
        <th><%= t('dashboard.services') %></th>
      </tr>
      </thead>
    </table>
  </div>
  <div class="panel_content no-padding panel_main">
    <% if stats.present? %>
      <table cellspacing="0" cellpadding="0" class="table-counts table-floating-header extra">
        <tbody>
          <% stats.each do |k, val| %>
            <tr>
              <td><%= k %></td>
              <td>
                <%= stat_link(val[:assessment], { filter: index_filters([
                    "child_status=#{Record::STATUS_OPEN}",
                    "owned_by=#{k}",
                    'record_state=true',
                    'assessment_due_dates'
                  ]
                )}, model) %>
              </td>
              <td>
                <%= stat_link(val[:case_plan], { filter: index_filters([
                    "child_status=#{Record::STATUS_OPEN}",
                    "owned_by=#{k}",
                    'record_state=true',
                    'case_plan_due_dates'
                  ]
                )}, model) %>
              </td>
              <td>
                <%= stat_link(val[:follow_up], { filter: index_filters([
                    "child_status=#{Record::STATUS_OPEN}",
                    "owned_by=#{k}",
                    'record_state=true',
                    'followup_due_dates'
                  ]
                )}, model) %>
              </td>
              <td>
                <%= stat_link(val[:services], { filter: index_filters([
                    "child_status=#{Record::STATUS_OPEN}",
                    "owned_by=#{k}",
                    'record_state=true',
                    "service_due_dates=#{overdue}"
                  ]
                )}, model) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="no-content"><%= t('dashboard.no_case_stats') %></p>
    <% end %>
  </div>
</div>

app/views/home/_case_manager_totals_by_risk_level.html.erb
<% @risk_levels.each do | risk_level| %>
  <%= display_stat_detailed({
    name: :risk_level,
    stat: "#{risk_level}_total".to_sym,
    filters: [
      "child_status=#{Record::STATUS_OPEN}",
      "risk_level=#{risk_level}",
      'record_state=true'
    ],
    additional_details: [
      {
        stat: risk_level.to_sym,
        filters: [
          "child_status=#{Record::STATUS_OPEN}",
          "risk_level=#{risk_level}",
          'new_other',
          'record_state=true'
        ],
        text: t('dashboard.new')
      }
    ],
    stats: stats,
    model: model,
    text: t("dashboard.#{risk_level}_risk"),
  }) %>
<% end %>

app/views/home/_case_manager_transfers.html.erb
<div class="panel dash_reporting_location">
  <div class="panel_header">
    <h4><%= t("dashboard.transfers_by_social_worker")  %></h4>
    <table cellspacing="0" cellpadding="0" class="table-counts table-floating-header">
      <thead>
      <tr>
        <th></th>
        <th><%= t('dashboard.total') %></th>
      </tr>
      </thead>
    </table>
  </div>
  <div class="panel_content no-padding panel_main">
    <% if stats.present? %>
      <table cellspacing="0" cellpadding="0" class="table-counts table-floating-header extra">
        <tbody>
          <% stats.each do |k, v| %>
            <tr>
              <td class="id_column"><%= I18n.t("transfer.search.#{k}") %></td>
              <td>
                <%= stat_link(v[:total_cases], {filter: index_filters(["child_status=#{Record::STATUS_OPEN}", "transfer_status=#{k}" ,'record_state=true'])}, model) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="no-content"><%= t('dashboard.no_case_stats') %></p>
    <% end %>
  </div>
</div>

app/views/home/_flagged_by_me.html.erb
<div class="panel">
 <div class="panel_header">
  <h4><%= t("dashboard.flagged_by_me") %></h4>
 </div>
 <div class="panel_content panel_xl">
  <ul>
    <% if flagged_by_me.present? %>
      <% flagged_by_me.each do |r| %>
        <li>
          <%= link_to link_dashboard_title(r), link_dashboard_path(r) %>
          <p><%= r[:message] %></p>
          <small><%= t('dashboard.flagged_by') %> <%= r[:flagged_by] || t('dashboard.system_user') %></small>
        </li>
      <% end %>
    <% else %>
      <li class="no-content"><%= t("dashboard.no_flagged_#{model.name.underscore}") %></li>
    <% end %>
  </ul>
   <% if flagged_by_me.present? %>
     <%= link_to t("dashboard.link_see_all"), index_link_dashboard_path(model), class: 'uppercase more' %>
   <% end %>
 </div>
</div>

app/views/home/_flagged_by_others.html.erb
<div class="panel">
 <div class="panel_header">
  <h4><%= t("dashboard.flagged_by_other") %></h4>
 </div>
 <div class="panel_content panel_xl">
  <ul>
    <% if flagged_by_others.present? %>
      <% flagged_by_others.each do |r| %>
        <li>
          <%= link_to link_dashboard_title(r), link_dashboard_path(r) %>
          <p><%= r[:message] %></p>
          <small><%= t('dashboard.flagged_by') %> <%= r[:flagged_by] || t('dashboard.system_user') %></small>
        </li>
      <% end %>
    <% else %>
      <li class="no-content"><%= t("dashboard.no_flagged_#{model.name.underscore}") %></li>
    <% end %>
  </ul>
   <% if flagged_by_others.present? %>
     <%= link_to t("dashboard.link_see_all"), index_link_dashboard_path(model), class: 'uppercase more' %>
   <% end %>
 </div>
</div>

app/views/home/_match_result_statistics.html.erb
<div class="panel dash_matching_results">
  <div class="panel_header">
    <h4><%= t('dashboard.match_result').html_safe  %></h4>
    <table cellspacing="0" cellpadding="0" class="table-counts table-floating-header">
      <thead>
      <tr>
        <th>
          <%= t('dashboard.score_range').html_safe %>
        </th>
        <th>
          <%= t('dashboard.range4').html_safe %>
        </th>
        <th>
          <%= t('dashboard.range4_8').html_safe %>
        </th>
        <th>
          <%= t('dashboard.range8_12').html_safe %>
        </th>
        <th>
          <%= t('dashboard.range12+').html_safe %>
        </th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= t('dashboard.case_stats').html_safe %></td>
        <td><%= match_stats[:range_case_1].to_i %></td>
        <td><%= match_stats[:range_case_2].to_i %></td>
        <td><%= match_stats[:range_case_3].to_i %></td>
        <td><%= match_stats[:range_case_4].to_i %></td>
      </tr>
      <tr>
        <td><%= t('dashboard.tr_stats').html_safe %></td>
        <td><%= match_stats[:range_tr_1].to_i %></td>
        <td><%= match_stats[:range_tr_2].to_i %></td>
        <td><%= match_stats[:range_tr_3].to_i %></td>
        <td><%= match_stats[:range_tr_4].to_i %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_new_assigned.html.erb
<div class="panel">
 <div class="panel_header">
  <h4><%= t("dashboard.new_#{model.name.underscore}_assigned_to_you") %></h4>
 </div>
 <div class="panel_content">
  <ul>
    <% records.each do |c| %>
      <li><%= link_to link_dashboard_title(c), link_dashboard_path(c) %></li>
    <% end %>
  </ul>
 </div>
</div>

app/views/home/_recent_activities.html.erb
<div class="panel">
  <div class="panel_header">
    <h4><%= t("dashboard.recent_activities") %></h4>
    <table cellspacing="0" cellpadding="0" class="table-floating-header">
      <thead>
      <tr>
        <th>
          <%= t("dashboard.case_id") %>
        </th>
        <th>
          <%= t("dashboard.name_or_survivor_code") %>
        </th>
        <th>
          <%= t("dashboard.current_owner") %>
        </th>
        <th>
          <%= t("dashboard.last_updated") %>
        </th>
      </tr>
      </thead>
    </table>
  </div>
  <div class="panel_content no-padding panel_main">
    <% if recent_activities.present? %>
      <table cellspacing="0" cellpadding="0" class="table-floating-header">
        <tbody>
          <% recent_activities.each do |s| %>
            <tr>
              <td class="id_column"><%= link_to s[:short_id], case_path(s[:_id]), class: 'id_link' %></td>
              <td><%= s[:module_id] == PrimeroModule::GBV ? s[:survivor_code_no] : s[:name] %></td>
              <td><%= s[:owned_by] %></td>
              <td><%= field_format_date(s[:last_updated_at]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="no-content"><%= t("dashboard.no_recent_activities") %></p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div id="dashboard">
  <div class="index_controls_container" data-top="49" data-bottom="40">
    <div class="row collapse">
      <div class="large-12 columns">
      </div>
    </div>
  </div>
  <% if @display_admin_only %>
    <%= render 'admin_only_index' %>
  <% else %>
    <% if @display_cases_dashboard %>
      <div class="row">
        <div id="content" class="large-9 small-9 columns dashboards">
          <% if @display_reporting_location %>
            <%= render 'case_admin_reporting_location_totals', reporting_location_stats: @reporting_location_stats,
                       model: Child, reporting_location: @reporting_location, admin_level: @admin_level%>
          <% end %>
          <% if @display_protection_concerns %>
            <%= render 'case_protection_concerns', protection_concern_stats: @protection_concern_stats,
                       model: Child, reporting_location: @reporting_location, admin_level: @admin_level %>
          <% end %>
          <% if @display_manager_dashboard %>
            <%= render 'case_manager_case_totals', records: @aggregated_case_worker_stats, model: Child %>
          <% end %>
          <% if @display_case_worker_dashboard %>
            <%= render 'case_counts',
                       new_cases: @new_cases,
                       total_cases: @total_cases,
                       model: Child
            %>
          <% end %>
          <% if @display_matching_results_dashboard %>
            <%= render 'match_result_statistics', match_stats: @match_stats, model: PotentialMatch %>
          <% end %>
        </div>
        <div id="sidebar" class="large-3 small-3 columns">
          <%= render 'flagged_by_me', flagged_by_me: @flagged_by_me, model: Child %>
          <% unless @display_manager_dashboard %>
            <%= render 'flagged_by_others', flagged_by_others: @flagged_by_others, model: Child %>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @display_incidents_dashboard %>
        <div class="row">
          <div id="content" class="large-9 small-9 columns dashboards">
            <%= render 'open_incidents', open_incidents: @open_incidents %>
          </div>
          <div id="sidebar" class="large-3 small-3 columns no-padding-left">
            <%= render 'flagged_by_me', flagged_by_me: @incidents_recently_flagged, model: Incident %>
          </div>
        </div>
    <% end %>

    <% if @display_gbv_incidents_dashboard %>
        <div class="row">
          <div id="content" class="large-9 small-9 columns dashboards">
            <%= render 'open_gbv_incidents', open_incidents: @open_gbv_incidents %>
          </div>
          <div id="sidebar" class="large-3 small-3 columns no-padding-left">
            <%= render 'flagged_by_me', flagged_by_me: @gbv_incidents_recently_flagged, model: Incident %>
          </div>
        </div>
    <% end %>
  <% end %>
</div>