config/routes.rb
  match '/incidents/:id/flag' => 'record_flag#flag', :as => :incident_flag, model_class: 'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/flag' => 'record_flag#flag', :as => :tracing_request_flag, model_class: 'TracingRequest', :via => [:post, :put]

#Flag multiple records routing
  match '/cases/flag_records' => 'record_flag#flag_records', :as => :child_flag_records, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/flag_records' => 'record_flag#flag_records', :as => :incident_flag_records, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/flag_records' => 'record_flag#flag_records', :as => :tracing_request_flag_records, :model_class => 'TracingRequest', :via => [:post, :put]

# Set Record Status
  match '/cases/record_status' => 'record_status#set_record_status', :as => :child_record_status, :model_class => 'Child', :via => [:post, :put]
  match '/incidents/record_status' => 'record_status#set_record_status', :as => :incident_record_status, :model_class => 'Incident', :via => [:post, :put]
  match '/tracing_requests/record_status' => 'record_status#set_record_status', :as => :tracing_request_record_status, :model_class => 'TracingRequest', :via => [:post, :put]

  # Set Case Status on reopening
  match '/cases/:id/reopen_case' => 'children#reopen_case', :as => :child_reopen_case, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/request_approval' => 'children#request_approval', :as => :child_request_approval, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/transfer_status' => 'children#transfer_status', :as => :child_transfer_status, :model_class => 'Child', :via => [:post, :put]
  match '/cases/:id/relinquish_referral' => 'children#relinquish_referral', :as => :child_relinquish_referral, :model_class => 'Child', :via => [:post, :put]

  # Download forms spreadsheet
  match '/forms/download' => 'form_section#download_all_forms', :as => :download_forms, :via => [:get]

  #Unflag routing
  match '/cases/:id/unflag' => 'record_flag#unflag', :as => :child_unflag, model_class:'Child', :via => [:post, :put]
  match '/incidents/:id/unflag' => 'record_flag#unflag', :as => :incident_unflag, model_class:'Incident', :via => [:post, :put]
  match '/tracing_requests/:id/unflag' => 'record_flag#unflag', :as => :tracing_request_unflag, model_class:'TracingRequest', :via => [:post, :put]

  match '/tracing_requests-ids' => 'tracing_request_ids#all', :as => :tracing_request_ids, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:id/photo/edit' => 'tracing_requests#edit_photo', :as => :edit_tracing_requests_photo, :via => :get
  match '/tracing_requests/:id/photo' => 'tracing_requests#update_photo', :as => :update_tracing_requests_photo, :via => :put
  match '/tracing_requests/:tracing_request_id/photos_index' => 'tracing_request_media#index', :as => :tracing_request_photos_index, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/photos' => 'tracing_request_media#manage_photos', :as => :manage_tracing_request_photos, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/document/:document_id' => 'tracing_request_media#download_document', :as => :tracing_request_document, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/audio(/:id)' => 'tracing_request_media#download_audio', :as => :tracing_request_audio, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/photo/:photo_id' => 'tracing_request_media#show_photo', :as => :tracing_request_photo, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/photo' => 'tracing_request_media#show_photo', :as => :tracing_request_legacy_photo, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/select_primary_photo/:photo_id' => 'tracing_requests#select_primary_photo', :as => :tracing_requests_select_primary_photo, :via => :put
  match '/tracing_requests/:tracing_request_id/resized_photo/:size' => 'tracing_request_media#show_resized_photo', :as => :tracing_request_legacy_resized_photo, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/photo/:photo_id/resized/:size' => 'tracing_request_media#show_resized_photo', :as => :tracing_request_resized_photo, :via => [:post, :get, :put, :delete]
  match '/tracing_requests/:tracing_request_id/thumbnail(/:photo_id)' => 'tracing_request_media#show_thumbnail', :as => :tracing_request_thumbnail, :via => [:post, :get, :put, :delete]
  match '/tracing_requests' => 'tracing_requests#index', :as => :tracing_request_filter, :via => [:post, :get, :put, :delete]

#######################
# RECORD HISTORIES URLS
#######################
  match '/cases/:id/change_log' => 'record_histories#record_change_log', :as => :child_record_change_log, model_class: 'Child', :via => [:get]
  match '/incidents/:id/change_log' => 'record_histories#record_change_log', :as => :incident_record_change_log, model_class: 'Incident', :via => [:get]
  match '/tracing_requests/:id/change_log' => 'record_histories#record_change_log', :as => :tracing_request_record_change_log, model_class: 'TracingRequest', :via => [:get]

#######################
# INCIDENT URLS
#######################
  resources :incidents do
    collection do
      # post :sync_unverified
      post :import_file
      post :mark_for_mobile
      # get :advanced_search
      get :search
    end

    # resources :attachments, :only => :show
    # resource :duplicate, :only => [:new, :create]
  end

  match '/incidents/:incident_id/document/:document_id' => 'incident_media#download_document', :as => :incident_document, :via => [:post, :get, :put, :delete]
  match '/incidents/:incident_id/create_cp_case_from_individual_details/:individual_details_subform_section' => 'incidents#create_cp_case_from_individual_details', :as => :create_cp_case_from_individual_details, :via => [:post, :get]

#######################
# POTENTIAL MATCHES URLS
#######################
  resources :potential_matches do
    collection do
      post :import_file
      get :quick_view
    end
  end
  # match '/potential_matches/:method' => 'potential_matches#index', :as => :potential_matches_method, :via => [:post, :get, :put, :delete]



  resources :bulk_exports, only: [:index, :show]
  resources :tasks, only: [:index]


#######################
# FORM SECTION URLS
#######################

  resources :form_sections, :path => 'forms', :controller => 'form_section' do
    collection do
      match 'save_order', :via => [:post, :get, :put, :delete]
      match 'toggle', :via => [:post, :get, :put, :delete]
      match 'published', :via => [:post, :get, :put, :delete]
      post :import_file
    end

    resources :fields, :controller => 'fields' do
      collection do
        post 'save_order'
        post 'delete'
        post 'toggle_fields'
        post 'change_form'
      end
    end
  end

  resources :highlight_fields do
    collection do
      post :remove
    end
  end

  match '/published_form_sections', :to => 'form_section#published', :via => [:post, :get, :put, :delete]


#######################
# API URLS
#######################

  scope '/api', defaults: { format: :json }, constraints: { format: :json } do
    #Session API
    post :login, to: 'sessions#create'
    post :logout, to: 'sessions#destroy'

    #Forms API
    resources :form_sections, controller: 'form_section', only: [:index]
    resources :form_sections, controller: 'form_section', as: :forms, path: :forms, only: [:index]

    #Records API
    resources :children
    resources :children, as: :cases, path: :cases
    resources :incidents, as: :incidents
    resources :tracing_requests, as: :tracing_requests
    resources :potential_matches, as: :potential_matches
    resources :options, :only => [:index]
    resources :system_settings, :only => [:index]
  end

#######################
# ADVANCED SEARCH URLS
#######################

  resources :advanced_search, :only => [:index, :new]
  match 'advanced_search/index', :to => 'advanced_search#index', :via => [:post, :get, :put, :delete]
  match 'advanced_search/export_data' => 'advanced_search#export_data', :as => :export_data_children, :via => :post


  match 'configuration_bundle/export', :to => 'configuration_bundle#export_bundle', :via => [:get, :post]
  match 'configuration_bundle/import', :to => 'configuration_bundle#import_bundle', :via => [:post]


#######################
# LOGGING URLS
#######################

  resources :system_logs, :only => :index
  match '/children/:id/history' => 'child_histories#index', :as => :child_history, :via => :get
  match '/incidents/:id/history' => 'incident_histories#index', :as => :incident_history, :via => :get
  match '/tracing_requests/:id/history' => 'tracing_request_histories#index', :as => :tracing_request_history, :via => :get
  match '/cases/:id/history' => 'child_histories#index', :as => :cases_history, :via => :get
  match '/users/:id/history' => 'user_histories#index', :as => :user_history, :via => :get

  resources :audit_logs, only: [:index]

#######################
# REPLICATION URLS
#######################
  resources :replications do
    collection do
      post :configuration
      post :update_blacklist
    end

    member do
      post :start
      post :stop
    end
  end

  resources :system_users, :path => "/admin/system_users"

#######################
# REPORTING URLS
#######################
  resources :reports do
    member do
      get :graph_data
      #put :rebuild
    end
    collection do
      get :permitted_field_list
      get :lookups_for_field
    end
  end

#######################
# CUSTOM EXPORT URLS
#######################
  resources :custom_exports do
    collection do
      get :permitted_forms_list
      get :permitted_fields_list
      get :export
    end
  end

#######################
# LOOKUPS URLS

app/models/reports/date_range.rb
module Reports

  class DateRange

    MIN = Date.new

    attr_accessor :date

    def initialize(date_string)
      self.date = Date.parse(date_string) rescue MIN
    end

    def core_value
      self.date
    end

    def <=>(other)
      self.core_value <=> other.core_value
    end

    def eql?(other)
      self.core_value.eql?(other.core_value)
    end

    def hash
      core_value.hash
    end

    def format
      '%d-%b-%Y'
    end

    def to_s
      if date.present? && date > MIN
        date.strftime(format)
      else
        ''
      end
    end

  end

end

app/models/reports/month_range.rb
module Reports

  class MonthRange < DateRange

    def core_value
      [self.date.year, self.date.month]
    end

    def format
      '%b-%Y'
    end

  end

end

app/models/reports/utils.rb
  module Reports

  class Utils

    def self.group_values(values, group_pivot_index)
      result = values
      if group_pivot_index.present?
        result = {}
        group_buckets = values.group_by do |pivot, _|
          group_value = yield(pivot[group_pivot_index])
          group_value ||= ''
          if group_pivot_index > 0
            pivot[0..(group_pivot_index-1)] + [group_value]
          else
            [group_value]
          end
        end
        #for every bucket, merge the contents
        group_buckets.each do |group, bucket|
          merge_buckets = bucket.group_by do |pivots|
            if group_pivot_index < pivots[0].size - 1
              pivots[0][(group_pivot_index+1)..-1]
            else
              []
            end
          end
          #Total the pivot counts for each merge bucket
          merge_buckets.each do |merge, merge_bucket|
            count = merge_bucket.reduce(0) do |sum, b|
              sum + (b[1] ? b[1] : 0)
            end
            #Add the new row to the result
            merged_pivot = group + merge
            result[merged_pivot] = count
          end
        end
      end
      return result
    end

    def self.date_range(date_string, type)
      type = type.present? ? type : 'date'
      range_clazz = Kernel.const_get("Reports::#{type.capitalize}Range")
      range_clazz.new(date_string)
    end

    def self.correct_aggregate_counts(values)
      if values.present?
        number_of_pivots = values.first.first.size
        if number_of_pivots > 1
          (number_of_pivots-1).downto(0).each do |i|
            values.group_by{|pivots, value| pivots[0..i]}.each do |pivot_group, values_in_group|
              pivots = pivot_group + [""] * (number_of_pivots - pivot_group.size)
              sum = values_in_group.reduce(0) do |sum, pivot_value|
                pivot_value[0].last.present? ? sum + pivot_value[1] : sum
              end
              values[pivots] = sum
            end
          end
        end
      end
      return values
    end

  end

end

app/models/reports/week_range.rb
module Reports

  class WeekRange < DateRange

    def core_value
      [self.date.year, self.date.cweek]
    end

    def to_s
      if date.present? && date > MIN
        "#{date.beginning_of_week.strftime(format)} - #{date.end_of_week.strftime(format)}"
      else
        ''
      end
    end

  end

end

app/models/reports/year_range.rb
module Reports

  class YearRange < DateRange

    def core_value
      self.date.year
    end

    def format
      '%Y'
    end

  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  # Creates a histogram out of an array, preserving the order and creating
  # a new count for identical but separated elements
  # pattern_histogram(["a","a","b","a"])
  # =>
  # [["a",2],["b",1],["a",1]]
  def pattern_histogram(array)
    result = []
    previous = nil
    array.each do |element|
      if element != previous || !element.present?
        result << [element, 1]
      else
        result[-1][1] = result[-1][1] + 1
      end
      previous = element
    end
    return result
  end

  # Compute the complex headers for the disaggregate fields.
  # There will be a row for every disaggregate pivot nest
  def report_header_rows(disaggregate_fields)
    header_rows = []
    if disaggregate_fields.present?
      disaggregate_fields.first.length.times.each do |i|
        header_rows << pattern_histogram(disaggregate_fields[1..-1].map{|v|v[i]})
      end
      header_rows.length.times.each do |i|
        row = header_rows[i]
        previous = nil
        row.length.times.each do |j|
          value = row[j][0]
          if value != previous && previous == ""
            header_rows[i][j-1] = [t('report.all'), header_rows[i][j-1][1]]
          end
          previous = value
        end
      end
      #Append a totals column
      if header_rows.size > 0
        header_rows.first << [t('report.total'), 1]
        header_rows[1..-1].each do |row|
          row << ["", 1]
        end
      end
    end
    unless header_rows.present?
      header_rows = [[[t('report.total'),1]]]
    end
    return header_rows
  end

  def report_sidebar_value(aggregate_value)
    value = ""
    aggregate_value.reverse_each do |v|
      if v.present?
        value = v
        break
      end
    end
    return value
  end

  def report_row_type(aggregate_value)
    if aggregate_value.last.present?
      'report_row_values'
    else
      'report_row_aggregate'
    end
  end

  # Assumes grouped fields is a hash that resembles:
  # {
  #    "module_name" => [
  #      "form_name", [
  #         ["field_name", "field_display_name", "field_type"]**
  #      ]**
  #    ]**
  # }
  def select_options_fields_grouped_by_form(grouped_fields, include_type=false)
    unique_fields = Set.new
    grouped_fields_options = []
    if grouped_fields.present?
      grouped_fields.keys.each do |module_name|
        grouped_fields[module_name].each do |form|
          form_array = ["#{form[0]} (#{module_name})", []]
          form[1].each do |field|
            if unique_fields.add? field[0]
              form_array[1] << [field[1], field[0]]
              form_array[1].last << field[2] if include_type
            end
          end
          grouped_fields_options << form_array
        end
      end
    end
    return grouped_fields_options
  end

end

app/views/reports/_editable.html.erb
<%
  editable = object.name.present?
  given_locale = object.base_language
%>
<% if editable %>
  <div class="row">
    <div class="medium-3 medium-offset-5 columns">
      <label class="key inline"><%= t(:provide_translation) %></label>
    </div>
    <div class="medium-4 columns">
      <div class="lang_title">
        <%= select_tag("locale", options_for_select(Primero::Application::locales_with_description.reject { |option| option.last == Primero::Application::default_locale }), :class => 'locale') %>
      </div>
    </div>
  </div>
<% end %>

<%= resource_edit_field(object, "name_#{given_locale}", 'report.name', 'text_field', true, false, nil, 'errors.models.report.name_presence') %>
<% if editable %>
  <% Primero::Application::locales.each do |new_locale| %>
    <% if new_locale != "en" %>
      <div class="row <%= "translation_forms #{new_locale}"%> hide_element">
        <div class="row"><div class="large-offset-3"><small><%= t("home.#{new_locale}")  %></small></div></div>
        <%= resource_edit_field(object, "name_#{new_locale}", nil, 'text_field', false, false, nil, 'errors.models.report.name_presence') %>
      </div>
    <% end %>
  <% end %>
<% end %>

<%= resource_edit_field(object, "description_#{given_locale}", 'report.description', 'text_area', false, false, nil, nil) %>

<% Primero::Application::locales.each do |new_locale| %>
  <% if new_locale != "en" %>
    <div class="row <%= "translation_forms #{new_locale}"%> hide_element">
      <div class="row"><div class="large-offset-3"><small><%= t("home.#{new_locale}")  %></small></div></div>
      <%= resource_edit_field(object, "description_#{new_locale}", nil, 'text_area') %>
    </div>
  <% end %>
<% end %>


<%# Modules input %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :module_ids, t("report.modules"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form">
      <%= form_builder.select(
        :module_ids,
        options_for_select(
          @current_user.modules.map{|p|[p.name, p.id]},
          @report.module_ids
        ),
        {},
        {multiple: true, :'data-placeholder' => t("fields.select_box_empty_item"), :required => ""}
      ) %>
      <small class="error"><%= t('errors.models.report.module_presence') %></small>
    </span>
  </div>
  <div class="medium-1 columns">
    <span class="required">*</span>
  </div>
</div>
<%# Record type input %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :record_type, t("report.record_type"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form">
      <%= form_builder.select(
        :record_type,
        options_for_select(
          Report.reportable_record_types.map{|rt|[t("forms.record_types.#{rt}"), rt]},
          @report.record_type
        ),
        {include_blank: t("fields.select_box_empty_item")},
        {:'data-placeholder' => t("fields.select_box_empty_item"), :required => ""}
      ) %>
      <small class="error"><%= t('errors.models.report.record_type_presence') %></small>
    </span>
  </div>
  <div class="medium-1 columns">
    <span class="required">*</span>
  </div>
</div>
<%# Report Rows / aggregate_by %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :aggregate_by, t("report.aggregate_by"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form" data-actual-order="<%= @report.aggregate_by %>">
      <%= form_builder.select(
        :aggregate_by,
        grouped_options_for_select(
          select_options_fields_grouped_by_form(@reportable_fields),
          @report.aggregate_by
        ),
        {},
        {multiple: true, :'data-placeholder' => t("fields.select_box_empty_item"), :required => ""}
      ) %>
      <small class="error"><%= t('errors.models.report.group_by_row_presence') %></small>
    </span>
    <p class="help"><%= t("reports.limited_pivots") %></p>
  </div>
  <div class="medium-1 columns">
    <span class="required">*</span>
  </div>
</div>
<%# Report Coulmns / disaggregate_by %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :disaggregate_by, t("report.disaggregate_by"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form" data-actual-order="<%= @report.disaggregate_by %>">
      <%= form_builder.select(
        :disaggregate_by,
        grouped_options_for_select(
          select_options_fields_grouped_by_form(@reportable_fields),
          @report.disaggregate_by
        ),
        {}, {multiple: true, :'data-placeholder' => t("fields.select_box_empty_item")}
      ) %>
    </span>
  </div>
  <div class="medium-1 columns">
    <span></span>
  </div>
</div>
<%# Aggregate counts from %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :aggregate_counts_from, t("report.aggregate_counts_from"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form">
      <%= form_builder.select(
        :aggregate_counts_from,
        grouped_options_for_select(
          select_options_fields_grouped_by_form(@reportable_fields_aggregate_counts_from),
          @report.aggregate_counts_from
        ),
        {include_blank: t("fields.select_box_empty_item")},
        {:'data-placeholder' => t("fields.select_box_empty_item")}
      ) %>
    </span>
  </div>
  <div class="medium-1 columns">
    <span></span>
  </div>
</div>
<%# Group ages%>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :group_ages, t("report.group_ages"), :class=>'key inline' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <%= form_builder.check_box :group_ages, {}, "true", "false" %>
    <small><%= @age_ranges ? @age_ranges.join(", ") : '' %></small>
  </div>
  <div class="medium-1 columns"> </div>
</div>
<%# Group dates by input %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :group_dates_by, t("report.group_dates_by"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <span class="value value_form">
      <%= form_builder.select(
        :group_dates_by,
        options_for_select(
          Report::DATE_RANGES.map{|r|[t("report.date_ranges.#{r}"), r]},
          @report.group_dates_by,
        ),
        {},
        {:required => ""}
      ) %>
      <small class="error"><%= t('errors.models.report.use_date_ranges_presence') %></small>
    </span>
  </div>
  <div class="medium-1 columns">
    <span class="required">*</span>
  </div>
</div>
<%# Filter by %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :filters, t("report.filters.label"), class: 'key' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <div class="report_filters_container">
      <% if @report.filters.present? %>
        <% @report.filters.each_with_index do |filter, index|%>
          <%= render partial: 'report_filter', locals: {report_filter: filter, index: index} %>
        <% end %>
      <% end %>
    </div>
    <%= render partial: 'report_filter', locals: {report_filter: nil, index: nil} %>
    <div class="row collapse">
      <div class="medium-5 columns medium-offset-8">
        <a id="report_filter_add_button" class="button">Add Filter</a>
      </div>
    </div>
  </div>
  <div class="medium-1 columns"></div>
</div>
<%# Add default filters %>
<% if @report.add_default_filters %>
  <div class="row">
    <div class="medium-3 columns">
      <span class="tool-tip-label">
        <%= form_builder.label :add_default_filters, t("report.add_default_filters"), :class=>'key inline' %>
      </span>
    </div>
    <div class="medium-8 columns">
      <%= form_builder.check_box :add_default_filters, {}, "true", "false" %>
      <small><%= t('report.add_default_filters_help') %></small>
    </div>
    <div class="medium-1 columns"> </div>
  </div>
<% end %>
<%# Report Is Graph %>
<div class="row">
  <div class="medium-3 columns">
    <span class="tool-tip-label">
      <%= form_builder.label :is_graph, t("report.is_graph"), :class=>'key inline' %>
    </span>
  </div>
  <div class="medium-8 columns">
    <%= form_builder.check_box :is_graph, {}, "true", "false" %>
  </div>
  <div class="medium-1 columns"> </div>
</div>

app/views/reports/_summary_row.html.erb
<tr>
  <% if false %>
  <td class="select_record">
    <input type="checkbox" class="select_record" value="<%= record.id %>" id="<%= record.name %>">
  </td>
  <% end %>
  <td id="report_<%= record.id %>" class="id_column">
    <%= link_to (record.name(I18n.locale).present? ? record.name(I18n.locale) : record.name_en), report_path(record), class: 'id_link' %>
  </td>
  <td><%= (record.description(I18n.locale).present? ? record.description(I18n.locale) : record.description_en) %></td>
  <td>
    <% if can?(:destroy, Report) && record.editable %>
        <%= link_to t("reports.actions.delete"), record, data: {confirm: t("reports.messages.confirmation")}, method: :delete %>
    <% end %>
  </td>
</tr>

app/views/reports/_toolbar.html.erb
<%#
    TODO: A very wet hack. Didn't refactor shared/record_controls.
    Should have. I'm so sorry, Josh
%>
<div class="record_controls_container" data-top="49" data-bottom="120">
  <div class="record_controls">
    <div class="row align-middle">
      <div class="large-3 medium-3 columns">
        <h4><%= @report.name %></h4>
      </div>
      <div class="large-9 medium-9 columns">
        <div class="row align-middle controls">
          <div class="large-12 columns">
            <div class="button-group">
              <%= link_to icon('angle-left') + t("buttons.back"), reports_path, class: 'button back-button' %>
              <% if controller.action_name != 'edit' %>
                <ul class="dropdown menu" data-dropdown-menu>
                  <li>
                    <%= link_to content_tag(:span, t("buttons.export")), '#', class: 'button action_btn' %>
                    <ul class="menu">
                      <% if @report.is_graph? %>
                        <li><%= link_to t("report.export.graph"), '#', class: 'report_export_graph', download: "#{@report.name.gsub(/\W/,'').downcase}_graph.png" %></li>
                      <% end %>
                      <li><%= link_to t("report.export.data"), '#', class: 'report_export_data',  download: "#{@report.name.gsub(/\W/,'').downcase}_data.csv" %></li>
                    </ul>
                  </li>
                </ul>
              <% end %>
              <% if @report.editable? && can?(:edit, @report) %>
                <%= render_controls(@report) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>

app/views/reports/edit.html.erb
<div class="reports_form">
    <%= render partial: 'shared_configuration_resource/edit', locals: {object: @report, opts: {show_side_tab: false}} %>
</div>

app/views/reports/index.html.erb
<%=
  render({
    partial: 'record_shared/list_view_table',
    locals: {
      model: Report,
      record: 'report',
      collection: @reports,
      opts: {
        display_actions: false,
        display_filter: false,
        display_create: true
      }
    }
  })
%>

app/views/reports/new.html.erb
<div class="reports_form">
<%= render partial: 'shared_configuration_resource/edit', locals: {object: @report, action: 'new', opts: {show_side_tab: false}} %>
</div>